title: Standard-Seite

navigation:
  status: all
  template: all

tabs:
  content:
    extends: tabs/content
  meta:
    extends: tabs/meta
  pages:
    extends: tabs/subpages
  files:
    extends: tabs/files
