title: Site

sections:
  home:
    type: pages
    create: false
    templates:
      - home
  pages:
    type: pages
    templatesIgnore:
      - home
      - error
  error:
    type: pages
    create: false
    templates:
      - error
